version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-20-bullseye
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - node-gitdb

  mongo:
    restart: always
    image: mongo:6.0.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - node-gitdb
    ports:
      - 27017:27017

volumes:
  mongo_data:

networks:
  node-gitdb: